system:
  addon_dir: "/Users/sbaildon/Desktop/addons/"
addons:
  - https://wow.curseforge.com/projects/big-wigs
  - https://wow.curseforge.com/projects/bad-boy
  - https://wow.curseforge.com/projects/details
  - http://www.wowinterface.com/downloads/info7032-TomTom.html
